docking_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_footprint"
    fixed_frame: "odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks supported
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.60
      use_external_detection_pose: true
      use_battery_status: false
      use_stall_detection: false

      # Controller for high-precision docking approach
      controller:
        plugin: 'nav2_graceful_controller::GracefulController'
        motion_target_dist: 0.25
        max_vel_x: 0.12
        max_vel_theta: 0.4
        k_phi: 2.0
        k_delta: 1.0
        beta: 0.4
        lambda: 2.0
