name: nav2-phase4

services:
  nav2:
    build:
      context: .
      dockerfile: Dockerfile
    image: nav2-phase4:jazzy
    container_name: nav2_phase4
    environment:
      ROS_DOMAIN_ID: 46
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      TURTLEBOT3_MODEL: waffle_pi
      NAV2_STARTUP_TIMEOUT: 300
      ROBOT_SPAWN_X: "-2.0"
      ROBOT_SPAWN_Y: "-0.5"
      ROBOT_SPAWN_YAW: "0.0"
      DISPLAY: host.docker.internal:0.0
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: "1"
      MESA_GL_VERSION_OVERRIDE: "3.3"
      MESA_GLSL_VERSION_OVERRIDE: "330"
    command: ["/start_nav2_phase4.sh"]
    stdin_open: true
    tty: true
